d={
    "add":"""O comando 'add' cadastra uma nova instancia no banco de dados.
SINTAXE: 'add [flag]'
> A [flag] e representada por um dos caracteres [r,a,v,s] e indica qual tipo de instancia
deve ser adicionada: [responsavel, ativo, vulnerabilidade, setor] respectivamente...
============
-> 'add v' inicia o cadastro de uma vulnerabilidade...
-> 'add a' inicia o cadastro de um ativo...
-> 'add s' inicia o cadastro de um setor...
-> 'add r' inicia o cadastro de um responsavel...
============""",
    "search":"""O comando 'search' inicia uma busca no banco de dados das instancias de um certo tipo.
SINTAXE: 'search [flag] [id/nm/ls] [termo de busca]'
> A [flag] e representada por um dos caracteres [r,a,v,s] e indica qual tipo de instancia
deve ser buscada: [responsavel, ativo, vulnerabilidade, setor] respectivamente...
> O primeiro argumento apos a flag possui dois caracteres entre 'id' para buscas diretas por ID;
'nm' para uma busca textural por nome; ou 'ls' para listar TODAS as instancias com a flag escolhida...
> O segundo argumento apos a flag e o termo de busca, o qual pode ser um numero de ID ou uma ou mais
palavras para a busca textual, a depender do primeiro argumento...
> Caso o primeiro argumento seja 'ls', nao e necessario digitar um termo de busca...
============
-> 'search s ls' lista TODOS os setores...
-> 'search r nm Gabriel' lista os responsaveis que possuem o termo "Gabriel" no NOME...
-> 'search a id 345' lista o ativo com ID igual a 345, se existir...
============""",
    "config":"""O comando 'config' abre um menu de preferencias.
SINTAXE: 'config'
> Nao e necessario digitar qualquer outro argumento...
> O menu de preferencias possui comandos a parte, explicados em si mesmo...
============""",
    "help":"""O comando 'help' escreve detalhes sobre algum comando do menu principal.
SINTAXE: 'help [comando]'
> O comando deve ser um dos comandos validos do menu principal: ['add','search','help','config','exit']...
============
-> 'help add' mostra detalhes sobre como executar o comando 'add'...
-> 'help search' mostra detalhes sobre como executar o comando 'search'...
============""",
    "exit":"""O comando 'exit', quando executado no menu principal, fecha o programa."""
}